CtrlPVALeasing/Controllers/GerencialController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CtrlPVALeasing.Models;
using System.IO;

namespace CtrlPVALeasing.Controllers
{
    public class GerencialController : Controller
    {
        private CtrlIPVALeasingContext db = new CtrlIPVALeasingContext();

        IEnumerable<ContratosVeiculosViewModel> model = null;
        Arm_Veiculos model2 = null;

        /// <summary>
        /// Cria um IEnumerable do modelo ContratosVeiculosViewModel vazio para se injetar na PARTIAL VIEW pela primeira vez quando ela carrega sem ninguém.
        /// Sem este IEnumarable epecífico para a Partial View ela lê o rodapé da _ViewStart na primeira vêz e imprime ele no local da partial View.
        /// </summary>
        /// <returns></returns>
        private IEnumerable<ContratosVeiculosViewModel> GetContratosVeiculosViewModelPrimeiraRodape()
        {
            List<ContratosVeiculosViewModel> model = new List<ContratosVeiculosViewModel>();
            model.Add(new ContratosVeiculosViewModel() { id = 0, agencia = "rodap" });
            return model;
        }

        /// <summary>
        /// Cria um IEnumerable do modelo ContratosVeiculosViewModel vazio para se injetar na view pela primeira vez quando ela carrega sem ninguém.
        /// </summary>
        /// <returns></returns>
        private IEnumerable<ContratosVeiculosViewModel> GetContratosVeiculosViewModelPrimeira()
        {
            List<ContratosVeiculosViewModel> model = new List<ContratosVeiculosViewModel>();
            model.Add(new ContratosVeiculosViewModel() { id = 0, agencia = " " });
            return model;
        }

        /// <summary>
        /// Cria um IEnumerable do modelo ContratosVeiculosViewModel com -1 para se injetar na view quando for retorno de pesquisa sem resposta dando erro.
        /// </summary>
        /// <returns></returns>
        private IEnumerable<ContratosVeiculosViewModel> GetContratosVeiculosViewModelErro()
        {
            List<ContratosVeiculosViewModel> model = new List<ContratosVeiculosViewModel>();
            model.Add(new ContratosVeiculosViewModel() { id = -1, agencia = " " });
            return model;
        }

        public ActionResult Menu()
        {
            return View();
        }

        public ActionResult PagamentoIPVAPorStatusContrato_ANTIGO()
        {
            model = (from a in db.Arm_LiquidadosEAtivos_Contrato
                     join b in db.Arm_Veiculos
                     on a.contrato equals b.contrato
                     join c in db.Tbl_DebitosEPagamentos_Veiculo
                     on new { b.chassi, b.renavam, b.placa } equals new { c.chassi, c.renavam, c.placa }
                     where a.origem.Equals("B")
                     where (!b.origem.Contains("RECIBO VEN") || b.origem == null)
                     select new
                     {
                         id = a.id,
                         contrato = a.contrato,
                         tipo = a.tipo,
                         agencia = a.agencia,
                         dta_inicio_contrato = a.dta_inicio_contrato,
                         dta_vecto_contrato = a.dta_vecto_contrato,
                         origem = a.origem,
                         cpf_cnpj_cliente = a.cpf_cnpj_cliente,
                         nome_cliente = a.nome_cliente,
                         ddd_cliente_particular = a.ddd_cliente_particular,
                         fone_cliente_particular = a.fone_cliente_particular,
                         rml_cliente_particular = a.rml_cliente_particular,
                         end_cliente = a.end_cliente,
                         bairro_cliente = a.bairro_cliente,
                         cidade_cliente = a.cidade_cliente,
                         uf_cliente = a.uf_cliente,
                         cep_cliente = a.cep_cliente,
                         filler = a.filler,
                         ddd_cliente_cml = a.ddd_cliente_cml,
                         fone_cliente_cml = a.fone_cliente_cml,
                         dta_ultimo_pagto = a.dta_ultimo_pagto,
                         tipo_de_baixa = a.tipo_de_baixa,
                         data_da_baixa = a.data_da_baixa,
                         cod_empresa = a.cod_empresa,
                         num_end_cliente = a.num_end_cliente,
                         comp_end_cliente = a.comp_end_cliente,
                         status = a.status,

                         contrato_v = b.contrato,
                         tipo_registro = b.tipo_registro,
                         marca = b.marca,
                         modelo = b.modelo,
                         tipo_v = b.tipo,
                         ano_fab = b.ano_fab,
                         ano_mod = b.ano_mod,
                         cor = b.cor,
                         renavam = b.renavam,
                         chassi = b.chassi,
                         placa = b.placa,
                         origem_v = b.origem,

                         valor_debito_total = c.valor_debito_total,
                         dta_cobranca = c.dta_cobranca,
                         uf_pagamento = c.uf_pagamento,
                         valor_divida = c.valor_divida,
                         ano_exercicio = c.ano_exercicio,
                         valor_custas = c.valor_custas,
                         pagamento_efet_banco = c.pagamento_efet_banco,
                         valor_recuperado = c.valor_recuperado,
                         valor_total_recuperado = c.valor_total_recuperado,
                         divida_ativa_serasa = c.divida_ativa_serasa,
                         uf_cobranca = c.uf_cobranca,
                         valor_pago_divida = c.valor_pago_divida,
                         valor_pago_custas = c.valor_pago_custas

                     }).AsEnumerable().Select(x => new ContratosVeiculosViewModel
                     {
                         id = x.id,
                         contrato = x.contrato,
                         tipo = x.tipo,
                         agencia = x.agencia,
                         dta_inicio_contrato = x.dta_inicio_contrato,
                         dta_vecto_contrato = x.dta_vecto_contrato,
                         origem = x.origem,
                         cpf_cnpj_cliente = x.cpf_cnpj_cliente,
                         nome_cliente = x.nome_cliente,
                         ddd_cliente_particular = x.ddd_cliente_particular,
                         fone_cliente_particular = x.fone_cliente_particular,
                         rml_cliente_particular = x.rml_cliente_particular,
                         end_cliente = x.end_cliente,
                         bairro_cliente = x.bairro_cliente,
                         cidade_cliente = x.cidade_cliente,
                         uf_cliente = x.uf_cliente,
                         cep_cliente = x.cep_cliente,
                         filler = x.filler,
                         ddd_cliente_cml = x.ddd_cliente_cml,
                         fone_cliente_cml = x.fone_cliente_cml,
                         dta_ultimo_pagto = x.dta_ultimo_pagto,
                         tipo_de_baixa = x.tipo_de_baixa,
                         data_da_baixa = x.data_da_baixa,
                         cod_empresa = x.cod_empresa,
                         num_end_cliente = x.num_end_cliente,
                         comp_end_cliente = x.comp_end_cliente,
                         status = x.status,

                         contrato_v = x.contrato_v,
                         tipo_registro = x.tipo_registro,
                         marca = x.marca,
                         modelo = x.modelo,
                         tipo_v = x.tipo_v,
                         ano_fab = x.ano_fab,
                         ano_mod = x.ano_mod,
                         cor = x.cor,
                         renavam = x.renavam,
                         chassi = x.chassi,
                         placa = x.placa,
                         origem_v = x.origem_v,

                         valor_debito_total = x.valor_debito_total,
                         dta_cobranca = x.dta_cobranca,
                         uf_pagamento = x.uf_pagamento,
                         valor_divida = x.valor_divida,
                         ano_exercicio = x.ano_exercicio,
                         valor_custas = x.valor_custas,
                         pagamento_efet_banco = x.pagamento_efet_banco,
                         valor_recuperado = x.valor_recuperado,
                         valor_total_recuperado = x.valor_total_recuperado,
                         divida_ativa_serasa = x.divida_ativa_serasa,
                         uf_cobranca = x.uf_cobranca,
                         valor_pago_divida = x.valor_pago_divida,
                         valor_pago_custas = x.valor_pago_custas
                     }).OrderByDescending(x => x.ano_exercicio).OrderByDescending(x => x.dta_cobranca);

            if (model.Count() == 0 || model == null)
            {
                return View(GetContratosVeiculosViewModelErro()); //RedirectToAction("ConsultaVeiculo");
            }

            if (model == null || model.Any() == false)
            {
                //return HttpNotFound();
                return RedirectToAction("PagamentoIPVAPorStatusContrato");
            }
            return View("PagamentoIPVAPorStatusContrato", model);
        }

        public ActionResult PagamentoIPVAPorStatusContrato(string escolha)
        {
            model = (from a in db.Arm_LiquidadosEAtivos_Contrato
                     join b in db.Arm_Veiculos
                     on a.contrato equals b.contrato

                     from c in db.Tbl_DebitosEPagamentos_Veiculo.Where(depv =>
                     (b.chassi == depv.chassi) || (b.renavam == depv.renavam) || (b.placa == depv.placa))

                     where a.origem.Equals("B")

CtrlPVALeasing/Views/Gerencial/ExportarTodaBaseArm.cshtml
@{
    Layout = null;
}
Erro: Deu estouro de memória!
O arquivo é muito grande e não pode ser exportado para um csv.

CtrlPVALeasing/Views/Gerencial/Menu.cshtml
@model IEnumerable<CtrlPVALeasing.Models.ContratosVeiculosViewModel>
<head>
    <meta name="viewport" content="width=device-width" />

    <!-- Este css dá conflito e faz as janelinhas de filtro do grid ficarem desalinhadas com o símbolo de filtro-->
    <!-- <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" /> -->
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")"></script>

    <!-- <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"> </script> -->

</head>
@{
    ViewBag.Title = "Menu Gerencial";
}

<div class="jumbotronFundo">
    <center>
        <table border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr>
                <th class="busca" width="90%">
                    <h2>SERVIÇOS DE GERENCIAMENTO</h2>
                </th>
                <th>
                    <a href="~/" class="btn2 btn-primary-menu btn-sm">MENU</a>
                </th>
            </tr>
        </table>
        <hr />
    </center>
    <table border="0">
        <tr>
            <td>
                <table border="1">
                    <tr>
                        <td>
                            <table border="0" style="border-style:inherit" width="100%">
                                <tr>
                                    <td>
                                        <table border="0" cellspacing="0" cellpadding="0" width="100%">
                                            <tr>
                                                <td>
                                                    <p><ul><li><font style="font-size: 14px;  font-weight: normal;  line-height: 1.428571429;">Pagamento de IPVA por Status de Contrato&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</font></li></ul>
                                                </td>
                                                <td>
                                                    <a href="~/Gerencial/PagamentoIPVAPorStatusContrato" class="btn2 btn-primary-cons btn-sm">CONSULTAR</a>&nbsp;
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <table border="0" cellspacing="0" cellpadding="0" width="100%">
                                            <tr>
                                                <td>
                                                    <p><ul><li><font style="font-size: 14px;  font-weight: normal;  line-height: 1.428571429;">Exportar Toda a Base ARM (Contratos e Veículos)&nbsp;&nbsp;</font></li></ul>
                                                </td>
                                                <td>
                                                    <a href="~/Gerencial/ExportarTodaBaseArm" class="btn2 btn-primary-imp .btn-sm">GERAR CSV</a>&nbsp;
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <table border="0" cellspacing="0" cellpadding="0" width="100%">
                                            <tr>
                                                <td>
                                                    <p><ul><li><font style="font-size: 14px;  font-weight: normal;  line-height: 1.428571429;">Veículos não Cadastrados com Débito&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</font></li></ul>
                                                </td>
                                                <td>
                                                    <a href="~/Gerencial/RegistroVeiculosComDebitoMasSemCadastro" class="btn2 btn-primary-imp .btn-sm">LISTAR</a>&nbsp;
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>

CtrlPVALeasing/Views/Gerencial/PagamentoIPVAPorStatusContrato.cshtml
@model IEnumerable<CtrlPVALeasing.Models.ContratosVeiculosViewModel>
<head>
    <meta name="viewport" content="width=device-width" />

    <!-- Este css dá conflito e faz as janelinhas de filtro do grid ficarem desalinhadas com o símbolo de filtro-->
    <!-- <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" /> -->
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")"></script>

    <!-- <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"> </script> -->

</head>
@{
    ViewBag.Title = "Pagamento de IPVA por Status de Contrato";
}

@using (Html.BeginForm("PagamentoIPVAPorStatusContrato", "Gerencial", FormMethod.Post, new { id = "FormAltera" }))
{
    <div class="jumbotronFundo">
        <input type="hidden" name="escolha" id="escolha" value="nada" />
        <center>
            <table border="0" cellpadding="0" cellspacing="0" width="100%">
                <tr>
                    <th class="busca" width="90%">
                        <h2>PAGAMENTO DE IPVA POR SATATUS DE CONTRATO</h2>
                    </th>

                    <th>
                        <a href="~/" class="btn2 btn-primary-menu btn-sm">MENU</a>
                    </th>
                </tr>
                <tr>
                    <td>
                        <input onclick="validateForm('gcvs');" class="btn4 btn-primary-imp .btn-sm" type="button" name="Submit" id="Submit" value="GERAR CSV" />
                    </td>

                </tr>
            </table>
            <hr />
        </center>

        <center>
            <table width="100%" border="1" cellspacing="0" cellpadding="10" style="border-style:inherit">
                <tr>
                    <td>
                        <b class="fonte-cinza-escuro">DADOS DOS CONTRATOS:</b>
                        <table border="0" style="border-style:inherit">
                            <tr>
                                <td>
                                    <div class="fonte-cinza-claro fonte-tamanho-form">Total de Contratos:&nbsp;&nbsp;&nbsp;</div>
                                </td>
                                @if (Model != null)
                                {
                                    @Html.Partial("_ContadorDeGrid")
                                }
                            </tr>
                            <tr>
                                <td class="input-sm-fino">&nbsp;</td>
                            </tr>
                            <tr>
                                @if (Model != null)
                                {
                                    @Html.Partial("_GridPagamentos")
                                }
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </center>

    </div>
}
<script>
    try {
        function validateForm(a) {
            if (a == "gcvs") {
                document.getElementById("escolha").value = "gcvs";
            }
            document.getElementById("FormAltera").submit();
            return true;
        }
    }
    catch (e) {
        alert("Erro: " + e);
    }
</script>

CtrlPVALeasing/Views/Gerencial/PagamentoIPVAPorStatusContrato_ANTIGO.cshtml
@model IEnumerable<CtrlPVALeasing.Models.ContratosVeiculosViewModel>
<head>
    <meta name="viewport" content="width=device-width" />

    <!-- Este css dá conflito e faz as janelinhas de filtro do grid ficarem desalinhadas com o símbolo de filtro-->
    <!-- <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" /> -->
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")"></script>

    <!-- <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"> </script> -->

</head>
@{
    ViewBag.Title = "Pagamento de IPVA por Status de Contrato";
}

    <div class="jumbotronFundo">

        <center>
            <table border="0" cellpadding="0" cellspacing="0" width="100%">
                <tr>
                    <th class="busca" width="90%"><h2>PAGAMENTO DE IPVA POR SATATUS DE CONTRATO</h2>
                    </th>

                    <th>
                        <a href="~/" class="btn2 btn-primary-menu btn-sm">MENU</a>
                    </th>
                </tr>
                <tr>
                    <td>
                        <div></div>
                    </td>

                </tr>
            </table>
            <hr />
        </center>

        <center>
            <table width="100%" border="1" cellspacing="0" cellpadding="10" style="border-style:inherit">
                <tr>
                    <td>
                        <b class="fonte-cinza-escuro">DADOS DOS CONTRATOS:</b>
                        <table border="0" style="border-style:inherit">
                            <tr>
                                <td>
                                    <div class="fonte-cinza-claro fonte-tamanho-form">Total de Contratos:&nbsp;&nbsp;&nbsp;</div>
                                </td>
                                @if (Model != null)
                                {
                                    @Html.Partial("_ContadorDeGrid")
                                }
                            </tr>
                            <tr>
                                <td class="input-sm-fino">&nbsp;</td>
                            </tr>
                            <tr>
                                @if (Model != null)
                                {
                                    @Html.Partial("_GridPagamentos")
                                }
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </center>

    </div>

CtrlPVALeasing/Views/Gerencial/RegistroVeiculosComDebitoMasSemCadastro.cshtml
@model IEnumerable<CtrlPVALeasing.Models.ContratosVeiculosViewModel>

@{
    ViewBag.Title = "Registro de Veículos com Débito mas Sem Cadastro";
}

@using (Html.BeginForm("RegistroVeiculosComDebitoMasSemCadastro", "Gerencial", FormMethod.Post, new { id = "FormAltera" }))
{
    <div class="jumbotronFundo">
        <input type="hidden" name="escolha" id="escolha" value="nada" />
        <center>
            <table border="0" cellpadding="0" cellspacing="0" width="100%">
                <tr>
                    <th class="busca" width="80%">
                        <h2>VEÍCULOS NÃO CADASTRADOS COM DÉBITO</h2>
                    </th>
                    <th style="vertical-align:bottom">
                        <a href="~/Gerencial/Menu" class="btn2 btn-primary-pesqui .btn-sm">VOLTAR</a>&nbsp;&nbsp;<a href="~/" class="btn2 btn-primary-menu btn-sm">MENU</a>
                    </th>
                </tr>
                <tr>
                    <td>
                        <input onclick="validateForm('rv');" class="btn4 btn-primary-imp .btn-sm" type="button" name="Submit" id="Submit" value="REGISTRAR VEÍCULOS" />
                    </td>
                </tr>
            </table>
            <hr />
        </center>

        <center>
            <table width="100%" border="1" cellspacing="0" cellpadding="10" style="border-style:inherit">
                <tr>
                    <td>
                        <b class="fonte-cinza-escuro">DADOS DOS VEÍCULOS:</b>
                        <table border="0" style="border-style:inherit">
                            <tr>
                                <td>
                                    <div class="fonte-cinza-claro fonte-tamanho-form">Total de Veículos:&nbsp;&nbsp;&nbsp;</div>
                                </td>
                                @if (Model != null)
                                {
                                    @Html.Partial("_ContadorDeVeiculos")
                                }
                            </tr>
                            <tr>
                                <td class="input-sm-fino">&nbsp;</td>
                            </tr>
                            <tr>
                                @if (Model != null)
                                {
                                    @Html.Partial("_GridDebitos")
                                }
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </center>

    </div>
}
@if (ViewBag.Message != null)
{
    <script>
        try {
            $(document).ready(function () {
                $("#msgOk").modal();
            });
        }
        catch (e) {
            alert(e);
        }
    </script>
}

<script>
    try {
        function validateForm(a) {
            if (a == "rv") {
                document.getElementById("escolha").value = "rv";
            }
            document.getElementById("FormAltera").submit();
            return true;
        }
    }
    catch (e) {
        alert("Erro: " + e);
    }
</script>

<div class="modal fade modal-sm" role="dialog" aria-labelledby="example-modal--label" aria-hidden="true" id="msgOk" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content modal-sm">
            <header class="modal-header modal-sm">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Fecha Janela</span></button>
                <center><h4 class="modal-title modal-sm" id="mySmallModalLabel" style="color:rgb(7, 44, 85)"><b>VEÍCULOS NÃO CADASTRADOS COM DÉBITO</b></h4></center>
            </header>
            <div class="modal-body modal-sm">
                <table width="100%">
                    <tr>
                        <td><center><h4 style="color: rgb(176, 172, 186)">@ViewBag.Message</h4></center></td>
                    </tr>
                    <tr>
                        <td align="right"><button type="button" class="btn btn-sm" data-dismiss="modal">Fechar</button></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

CtrlPVALeasing/Views/Gerencial/_ContadorDeGrid.cshtml
@model IEnumerable<CtrlPVALeasing.Models.ContratosVeiculosViewModel>

@{
    var contador = 0;
    foreach (var item in Model)
    {
        if (item.nome_cliente != "" && item.nome_cliente != null)
        {
            contador++;
        }
    }
}

<td colspan="7">
    <input class="input-sm-fino" value="@contador" type="text" name="contrato" maxlength="5" size="1" style="text-transform:uppercase" disabled="disabled" />
</td>

CtrlPVALeasing/Views/Gerencial/_ContadorDeVeiculos.cshtml
@model IEnumerable<CtrlPVALeasing.Models.ContratosVeiculosViewModel>

@{
    var contador = 0;
    foreach (var item in Model)
    {
        if ((item.chassi != null && item.chassi != "") || (item.renavam != null && item.renavam != "") || (item.placa != null && item.placa != ""))
        {
            contador++;
        }
    }
}

<td colspan="7">
    <input class="input-sm-fino" value="@contador" type="text" name="contrato" maxlength="5" size="1" style="text-transform:uppercase" disabled="disabled" />
</td>

CtrlPVALeasing/Views/Gerencial/_GridDebitos.cshtml
@model IEnumerable<CtrlPVALeasing.Models.ContratosVeiculosViewModel>

<table class="table" border="1" style="border-style:inherit">
    <tr>
        <td>
            <table class="table">
                <tr>
                    <th class="input-sm-fino">
                        <div class="fonte-cinza-claro fonte-tamanho-form">Nº</div>
                    </th>
                    <th class="input-sm-fino">
                        <div class="fonte-cinza-claro fonte-tamanho-form">Chassi</div>
                    </th>
                    <th class="input-sm-fino">
                        <div class="fonte-cinza-claro fonte-tamanho-form">Renavam</div>
                    </th>
                    <th class="input-sm-fino">
                        <div class="fonte-cinza-claro fonte-tamanho-form">Placa</div>
                    </th>
                </tr>

                @{var contadorInterno = 0;
                    foreach (var item in Model)
                    {
                        if ((item.chassi != null && item.chassi != "") || (item.renavam != null && item.renavam != "") || (item.placa != null && item.placa != ""))
                        {
                            contadorInterno++;
                            <tr>
                                <td class="input-sm-fino">
                                    @contadorInterno
                                </td>
                                <td class="input-sm-fino">
                                    @(item.chassi == null ? "" : item.chassi.ToString())
                                </td>
                                <td class="input-sm-fino">
                                    @(item.renavam == null ? "" : item.renavam.ToString())
                                </td>
                                <td class="input-sm-fino">
                                    @(item.placa == null ? "" : item.placa.ToString())
                                </td>
                            </tr>
                        }                        
                    }
                }
            </table>

        </td>
    </tr>
</table>