CtrlPVALeasing/Controllers/RelatorioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CtrlPVALeasing.Models;
using System.IO;

namespace CtrlPVALeasing.Controllers
{
    public class RelatorioController : Controller
    {
        private CtrlIPVALeasingContext db = new CtrlIPVALeasingContext();

        IEnumerable<ContratosVeiculosViewModel> model = null;

        /// <summary>
        /// Cria um IEnumerable do modelo ContratosVeiculosViewModel vazio para se injetar na view pela primeira vez quando ela carrega sem ninguém.
        /// </summary>
        /// <returns></returns>
        private IEnumerable<ContratosVeiculosViewModel> GetContratosVeiculosViewModelPrimeira()
        {
            List<ContratosVeiculosViewModel> model = new List<ContratosVeiculosViewModel>();
            model.Add(new ContratosVeiculosViewModel() { id = 0, agencia = " " });
            return model;
        }

        /// <summary>
        /// Model LINQ para o Relatório e para o CSV do RelatorioBensApreendidosDebtoIPVA
        /// </summary>
        private void ModelRelatorioBensApreendidosDebtoIPVA()
        {
            model = (from a in db.Arm_LiquidadosEAtivos_Contrato
                     join b in db.Arm_Veiculos
                     on a.contrato equals b.contrato

                     from c in db.Tbl_DebitosEPagamentos_Veiculo.Where(depv =>
                     (b.chassi == depv.chassi) || (b.renavam == depv.renavam) || (b.placa == depv.placa))

                     from d in db.Tbl_Bens.Where(bens =>
                     (b.chassi == bens.chassi) || (b.renavam == bens.renavam) || (b.placa == bens.placa))

                     join e in db.Tbl_CCL
                     on a.cpf_cnpj_cliente equals e.cpf_cnpj_cliente
                     into j1
                     from e in j1.DefaultIfEmpty() //Isto é um LEFT JOIN pra trazer quem esta na CCL e quem não está também.

                     where (c.pagamento_efet_banco == false || c.pagamento_efet_banco == null)

                     where a.origem.Equals("B")
                     where (!b.origem.Contains("RECIBO VEN") || b.origem == null)
                     select new
                     {
                         contrato = a.contrato,
                         status = a.status,
                         nome_cliente = a.nome_cliente,
                         cpf_cnpj_cliente = a.cpf_cnpj_cliente,
                         marca = e.marca,
                         chassi = b.chassi,
                         renavam = b.renavam,
                         placa = b.placa,
                         dta_cobranca = c.dta_cobranca,
                         uf_cobranca = c.uf_cobranca,
                         tipo_cobranca = c.tipo_cobranca,
                         valor_divida = c.valor_divida,
                         ano_exercicio = c.ano_exercicio,
                         pagamento_efet_banco = c.pagamento_efet_banco

                     }).AsEnumerable().Select(x => new ContratosVeiculosViewModel
                     {
                         contrato = x.contrato,
                         status = x.status,
                         nome_cliente = x.nome_cliente,
                         cpf_cnpj_cliente = x.cpf_cnpj_cliente,
                         marca = x.marca,
                         chassi = x.chassi,
                         renavam = x.renavam,
                         placa = x.placa,
                         dta_cobranca = x.dta_cobranca,
                         uf_cobranca = x.uf_cobranca,
                         tipo_cobranca = x.tipo_cobranca,
                         valor_divida = x.valor_divida,
                         ano_exercicio = x.ano_exercicio,
                         pagamento_efet_banco = x.pagamento_efet_banco

                     }).OrderByDescending(x => x.ano_exercicio).OrderByDescending(x => x.dta_cobranca);
        }

        public ActionResult RelatorioBensApreendidosDebtoIPVA()
        {
            ModelRelatorioBensApreendidosDebtoIPVA();
            return View("", model);
        }

        public ActionResult CSVdoRelatorioBensApreendidosDebtoIPVA()
        {
            //Gera Resultado em CSV.
            StringWriter sw = new StringWriter();

            sw.WriteLine("Nº Contrato; Status do Contrato; Nome do Cliente; CPF/CNPJ; Marca; Chassi; Renavam; Placa; Data da Cobrança; UF da Cobrança; Tipo de Cobrança; Valor da Dívida; Ano de Exercício");

            Response.ClearContent();
            Response.AddHeader("content-disposition", "attachment;filename=RelatorioBensApreendidosDebtoIPVA.csv");
            Response.ContentType = "application/octet-stream";
            Response.ContentEncoding = System.Text.Encoding.Default;

            var users = db.Tbl_DadosDaVenda.ToList();

            ModelRelatorioBensApreendidosDebtoIPVA();
            foreach (var elemento in model)
            {
                sw.WriteLine(string.Format("{0};{1};{2};{3};{4};{5};{6};{7};{8};{9};{10};{11};{12};",

                elemento.contrato,
                elemento.status,
                elemento.nome_cliente,
                elemento.cpf_cnpj_cliente,
                elemento.marca,
                elemento.chassi,
                elemento.renavam,
                elemento.placa,
                elemento.dta_cobranca,
                elemento.uf_cobranca,
                elemento.tipo_cobranca,
                elemento.valor_divida,
                elemento.ano_exercicio
                ));
            }
            Response.Write(sw.ToString());
            Response.End();

            return new EmptyResult();
        }

        /// <summary>
        /// Model LINQ para o Relatório e para o CSV do RelatorioCobrancasSimplesParaPagamento
        /// </summary>
        private void ModelRelatorioCobrancasSimplesParaPagamento()
        {
            model = (from a in db.Arm_LiquidadosEAtivos_Contrato
                     join b in db.Arm_Veiculos
                     on a.contrato equals b.contrato

                     from c in db.Tbl_DebitosEPagamentos_Veiculo.Where(depv =>
                     (b.chassi == depv.chassi) || (b.renavam == depv.renavam) || (b.placa == depv.placa))

                     from d in db.Tbl_Bens.Where(bens =>
                     (b.chassi == bens.chassi) || (b.renavam == bens.renavam) || (b.placa == bens.placa)).DefaultIfEmpty() //Isto é um LEFT JOIN
                     //join d in db.Tbl_Bens
                     //on new { b.chassi, b.renavam, b.placa } equals new { d.chassi, d.renavam, d.placa }
                     //into j0
                     //from d in j0.DefaultIfEmpty() //Isto é um LEFT JOIN

                     join e in db.Tbl_CCL
                     on a.cpf_cnpj_cliente equals e.cpf_cnpj_cliente
                     into j1
                     from e in j1.DefaultIfEmpty() //Isto é um LEFT JOIN pra trazer quem esta na CCL e quem não está também.

                     where (d.chassi == null || d.renavam == null || d.placa == null)

                     where (c.pagamento_efet_banco == false || c.pagamento_efet_banco == null)

                     where (e.marca.Equals("JUR") || e.marca == null)

                     where a.origem.Equals("B")
                     where (!b.origem.Contains("RECIBO VEN") || b.origem == null)
                     select new
                     {
                         contrato = a.contrato,
                         status = a.status,
                         nome_cliente = a.nome_cliente,
                         cpf_cnpj_cliente = a.cpf_cnpj_cliente,
                         marca = e.marca,
                         chassi = b.chassi,
                         renavam = b.renavam,
                         placa = b.placa,
                         dta_cobranca = c.dta_cobranca,
                         uf_cobranca = c.uf_cobranca,
                         tipo_cobranca = c.tipo_cobranca,
                         valor_divida = c.valor_divida,
                         ano_exercicio = c.ano_exercicio,
                         pagamento_efet_banco = c.pagamento_efet_banco

                     }).AsEnumerable().Select(x => new ContratosVeiculosViewModel
                     {
                         contrato = x.contrato,
                         status = x.status,
                         nome_cliente = x.nome_cliente,
                         cpf_cnpj_cliente = x.cpf_cnpj_cliente,
                         marca = x.marca,
                         chassi = x.chassi,
                         renavam = x.renavam,
                         placa = x.placa,
                         dta_cobranca = x.dta_cobranca,
                         uf_cobranca = x.uf_cobranca,
                         tipo_cobranca = x.tipo_cobranca,
                         valor_divida = x.valor_divida,
                         ano_exercicio = x.ano_exercicio,
                         pagamento_efet_banco = x.pagamento_efet_banco

                     }).OrderByDescending(x => x.ano_exercicio).OrderByDescending(x => x.dta_cobranca);
        }

        public ActionResult RelatorioCobrancasSimplesParaPagamento()
        {
            ModelRelatorioCobrancasSimplesParaPagamento();
            return View("", model);
        }

        public ActionResult CSVdoRelatorioCobrancasSimplesParaPagamento()
        {
            //Gera Resultado em CSV.
            StringWriter sw = new StringWriter();

            sw.WriteLine("Nº Contrato; Status do Contrato; Nome do Cliente; CPF/CNPJ; Marca; Chassi; Renavam; Placa; Data da Cobrança; UF da Cobrança; Tipo de Cobrança; Valor da Dívida; Ano de Exercício");

            Response.ClearContent();
            Response.AddHeader("content-disposition", "attachment;filename=RelatorioCobrancasSimplesParaPagamento.csv");
            Response.ContentType = "application/octet-stream";
            Response.ContentEncoding = System.Text.Encoding.Default;

CtrlPVALeasing/Views/Relatorio/EntradaRelatorioPerdasOperacionais.cshtml
@model IEnumerable<CtrlPVALeasing.Models.ContratosVeiculosViewModel>
<head>
    <meta name="viewport" content="width=device-width" />

    <!-- Este css dá conflito e faz as janelinhas de filtro do grid ficarem desalinhadas com o símbolo de filtro-->
    <!-- <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" /> -->
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")"></script>

    <!-- <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"> </script> -->

</head>
<script>
    function chamaErro1() {
        $(document).ready(function () {
            $("#msgErro1").modal();
        });
    }
</script>
@{
    ViewBag.Title = "Entrada de Datas - Relatório de Perdas Operacionais";
}

@using (Html.BeginForm("EntradaRelatorioPerdasOperacionais", "Relatorio", FormMethod.Post, new { id = "FormAltera", enctype = "multipart/form-data" }))
{
    var MF = Model.First();
        <div class="jumbotronFundo">
            <center>
                <table border="0" cellpadding="0" cellspacing="0" width="100%">
                    <tr>
                        <th class="busca" width="82%">
                            <h2>RELATÓRIO DE PERDAS OPERACIONAIS</h2>
                        </th>
                        <th class="busca" width="18%" align="right">
                            <br />
                            <a href="/" onclick="javascript: window.close();" class="btn2 btn-primary-pesqui .btn-sm">VOLTAR / MENU</a>
                        </th>
                    </tr>
                </table>
                <hr />
            </center>

            <center>
                <table width="100%" border="1" cellspacing="0" cellpadding="10" style="border-style:inherit">
                    <tr>
                        <td>
                            <b class="fonte-cinza-escuro">ENTRADA DE DATAS:</b>
                            <table border="0" style="border-style:inherit">
                                <tr>
                                    <td>
                                        <div class="fonte-cinza-claro fonte-tamanho-form">Data de Início do Pagamento:  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
                                    </td>
                                    <td>
                                        <input size="12" class="input-sm-fino" type="text" name="dataInicio" id="dataInicio" />
                                    </td>
                                    <td>
                                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    </td>
                                    <td>
                                        <div class="fonte-cinza-claro fonte-tamanho-form">Data de Fim do Pagamento:  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
                                    </td>
                                    <td>
                                        <input size="12" class="input-sm-fino" type="text" name="dataFim" id="dataFim" />
                                    </td>
                                    <td>
                                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    </td>
                                    <td>
                                        <input type="hidden" name="escolha" id="escolha" value="false" />
                                        <input onclick="validateForm(true);" class="btn4 btn-primary-imp .btn-sm" type="button" name="Submit" id="Submit" value="GERAR CSV" />
                                    </td>
                                    <td>
                                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    </td>
                                    <td>
                                        <input onclick="validateForm(false);" class="btn4 btn-primary-imp .btn-sm" type="button" name="Submit" id="Submit" value="GERAR RELATÓRIO" />
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </center>
        </div>


    @*//Erro de veículo não encontrado
    if (MF.id == -1)
    {
        <script>
            try
            {
                $(document).ready(function () {
                    $("#msgErro1").modal();
                });
            }
            catch (e) {
                alert(e);
            }
        </script>
    }*@
}
<script>

    try
    {
        function validateForm(a)
        {
            if (
                document.getElementsByName('dataInicio')[0].value == "" ||
                document.getElementsByName('dataFim')[0].value == ""
                )
            {
                $(document).ready(function () {
                    $("#msgErro1").modal();
                    return false;
                });
                return false;
            }
            else
            {
                if (a)
                {
                    document.getElementById("escolha").value = true;
                }
                else
                {
                    document.getElementById("escolha").value = false;
                }
                document.getElementById("FormAltera").submit();
                return true;
            }
            return false;
        }
    }
    catch(e)
    {
        alert(e);
    }

    $(document).ready(function () {
        $("#dataInicio").inputmask("mask", { "mask": "99/99/9999" });
        $("#dataFim").inputmask("mask", { "mask": "99/99/9999" });
    });

</script>

<div class="modal fade modal-sm" role="dialog" aria-labelledby="example-modal--label" aria-hidden="true" id="msgErro1" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content modal-sm">
            <header class="modal-header modal-sm">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Fecha Janela</span></button>
                <center><h4 class="modal-title modal-sm" id="mySmallModalLabel" style="color:rgb(7, 44, 85)"><b>REGISTRO DÉBITO DE IPVA</b></h4></center>
            </header>
            <div class="modal-body modal-sm">
                <table width="100%">
                    <tr>
                        <td><center><h4 style="color: rgb(206, 39, 39)">Observação:</h4><h4 style="color: rgb(176, 172, 186)"><font color="Black">Não é permitido deixar:</font><br /><br /><table><tr><td> - Data de Início</td></tr><tr><td> - Data de Fim</td></tr></table></h4><h4 style="color: rgb(206, 39, 39)">Em branco!</h4></center></td>
                    </tr>
                    <tr>
                        <td align="right"><button type="button" class="btn btn-sm" data-dismiss="modal">Fechar</button></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

CtrlPVALeasing/Views/Relatorio/RelatorioBensApreendidosDebtoIPVA.cshtml
@model IEnumerable<CtrlPVALeasing.Models.ContratosVeiculosViewModel>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
@{
    ViewBag.Title = "Relatório - Bens apreendidos com débito de IPVA";
    Layout = "~/Views/Shared/_LayoutImpressaoHorizontal.cshtml";
}
<h1>BENS APREENDIDOS COM DÉBITO DE IPVA</h1>
<br />
<table class="table" width="100%">
    <tr>
        <th>
            Nº Contrato
        </th>
        <th>
            Status do Contrato
        </th>
        <th>
            Nome do Cliente
        </th>
        <th>
            CPF/CNPJ
        </th>
        <th>
            Marca
        </th>
        <th>
            Chassi
        </th>
        <th>
            Renavam
        </th>
        <th>
            Placa
        </th>
        <th>
            Data da Cobrança
        </th>
        <th>
            UF da Cobrança
        </th>
        <th>
            Tipo de Cobrança
        </th>
        <th>
            Valor da Dívida
        </th>
        <th>
            Ano de Exercício
        </th>
        @*<th>
            pagamento_efet_banco
        </th>*@
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td align="center">
                @Html.DisplayFor(modelItem => item.contrato)
            </td>
            <td align="center">
                @(item.status.HasValue && item.status == true ? "Ativo" : (item.status.HasValue && item.status == false ? "Liquidado" : "" ))
            </td>
            <td align="left">
                @Html.DisplayFor(modelItem => item.nome_cliente)
            </td>
            <td align="right">
                @{
                    try
                    {
                        var resultado = "";
                        var cpfcnpjsemzeros = "";
                        if (@item.cpf_cnpj_cliente != "")
                        {
                            cpfcnpjsemzeros = @item.cpf_cnpj_cliente.TrimStart('0').Trim();
                        }

                        var p1 = "";
                        var p2 = "";
                        var p3 = "";
                        var p4 = "";
                        var p5 = "";

                        if (cpfcnpjsemzeros.Length > 11)
                        {
                            if (cpfcnpjsemzeros.Length == 14)
                            {
                                p1 = @cpfcnpjsemzeros.Substring(0, 2);
                                p2 = @cpfcnpjsemzeros.Substring(2, 3);
                                p3 = @cpfcnpjsemzeros.Substring(5, 3);
                                p4 = @cpfcnpjsemzeros.Substring(8, 4);
                                p5 = @cpfcnpjsemzeros.Substring(12, 2);
                                resultado = p1 + "." + p2 + "." + p3 + "/" + p4 + "-" + p5;
                            }
                            else if (cpfcnpjsemzeros.Length == 13)
                            {
                                p1 = @cpfcnpjsemzeros.Substring(0, 1);
                                p2 = @cpfcnpjsemzeros.Substring(1, 3);
                                p3 = @cpfcnpjsemzeros.Substring(4, 3);
                                p4 = @cpfcnpjsemzeros.Substring(7, 4);
                                p5 = @cpfcnpjsemzeros.Substring(11, 2);
                                resultado = "0" + p1 + "." + p2 + "." + p3 + "/" + p4 + "-" + p5;
                            }
                            else if (cpfcnpjsemzeros.Length == 12)
                            {
                                p1 = @cpfcnpjsemzeros.Substring(0, 3);
                                p2 = @cpfcnpjsemzeros.Substring(3, 3);
                                p3 = @cpfcnpjsemzeros.Substring(6, 4);
                                p4 = @cpfcnpjsemzeros.Substring(10, 2);
                                resultado = p1 + "." + p2 + "/" + p3 + "-" + p4;
                            }
                        }
                        else if (cpfcnpjsemzeros.Length == 11)
                        {
                            p1 = @cpfcnpjsemzeros.Substring(0, 3);
                            p2 = @cpfcnpjsemzeros.Substring(3, 3);
                            p3 = @cpfcnpjsemzeros.Substring(6, 3);
                            p4 = @cpfcnpjsemzeros.Substring(9, 2);

                            resultado = p1 + "." + p2 + "." + p3 + "-" + p4;
                        }
                        else if (cpfcnpjsemzeros.Length < 11)
                        {
                            for (int i = 0; i <= cpfcnpjsemzeros.Length; i += 3)
                            {
                                if (i < (cpfcnpjsemzeros.Length - 3))
                                {
                                    resultado += cpfcnpjsemzeros.Substring(i, 3) + ".";
                                }
                                else
                                {
                                    resultado += cpfcnpjsemzeros.Substring(i, cpfcnpjsemzeros.Length - i);
                                }

                                if (cpfcnpjsemzeros.Length < 4)
                                {
                                    resultado = cpfcnpjsemzeros;
                                }
                            }
                        }
                        @resultado
                    }
                    catch
                    {
                        @item.cpf_cnpj_cliente
                    }
                }
            </td>

            <td align="left">
                @Html.DisplayFor(modelItem => item.marca)
            </td>
            <td align="right">
                @Html.DisplayFor(modelItem => item.chassi)
            </td>
            <td align="right">
                @Html.DisplayFor(modelItem => item.renavam)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.placa)
            </td>
            <td align="center">
                @(item.status.HasValue ? item.dta_cobranca.ToString().Substring(0,10) : "")
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.uf_cobranca)
            </td>
            <td align="center">
                @(item.tipo_cobranca == "C" ? "Cobr.Simples" : (item.tipo_cobranca == "D" ? "Dív.Ativa" : ""))
            </td>
            <td align="right">
                @Html.DisplayFor(modelItem => item.valor_divida)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.ano_exercicio)
            </td>
            @*<td align="center">
                @Html.DisplayFor(modelItem => item.pagamento_efet_banco)
            </td>*@
        </tr>
    }
</table>

CtrlPVALeasing/Views/Relatorio/RelatorioCobrancaIPVAAreaBens.cshtml
@model IEnumerable<CtrlPVALeasing.Models.ContratosVeiculosViewModel>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
@{
    ViewBag.Title = "Relatório - Cobrança de IPVA - Área de Bens";
    Layout = "~/Views/Shared/_LayoutImpressaoHorizontal.cshtml";
}
<h1>COBRANÇA DE IPVA - ÁREA DE BENS</h1>
<br />
<table class="table">
    <tr>
        <th>
            Nº Contrato
        </th>
        <th>
            Status do Contrato
        </th>
        <th>
            Nome do Cliente
        </th>
        <th>
            CPF/CNPJ
        </th>
        <th>
            Marca
        </th>
        <th>
            Chassi
        </th>
        <th>
            Renavam
        </th>
        <th>
            Placa
        </th>
        <th>
            Valor da Dívida
        </th>
        <th>
            Valor das Custas
        </th>
        <th>
            Valor Débito Total
        </th>
        <th>
            Ano de Execício
        </th>
        <th>
            Valor Pago Total
        </th>
        @*<th>
            pagamento_efet_banco
        </th>*@
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td align="center">
                @Html.DisplayFor(modelItem => item.contrato)
            </td>
            <td align="center">
                @(item.status.HasValue && item.status == true ? "Ativo" : (item.status.HasValue && item.status == false ? "Liquidado" : "" ))
            </td>
            <td align="left">
                @Html.DisplayFor(modelItem => item.nome_cliente)
            </td>
            <td align="right">
                @{
                    try
                    {
                        var resultado = "";
                        var cpfcnpjsemzeros = "";
                        if (@item.cpf_cnpj_cliente != "")
                        {
                            cpfcnpjsemzeros = @item.cpf_cnpj_cliente.TrimStart('0').Trim();
                        }

                        var p1 = "";
                        var p2 = "";
                        var p3 = "";
                        var p4 = "";
                        var p5 = "";

                        if (cpfcnpjsemzeros.Length > 11)
                        {
                            if (cpfcnpjsemzeros.Length == 14)
                            {
                                p1 = @cpfcnpjsemzeros.Substring(0, 2);
                                p2 = @cpfcnpjsemzeros.Substring(2, 3);
                                p3 = @cpfcnpjsemzeros.Substring(5, 3);
                                p4 = @cpfcnpjsemzeros.Substring(8, 4);
                                p5 = @cpfcnpjsemzeros.Substring(12, 2);
                                resultado = p1 + "." + p2 + "." + p3 + "/" + p4 + "-" + p5;
                            }
                            else if (cpfcnpjsemzeros.Length == 13)
                            {
                                p1 = @cpfcnpjsemzeros.Substring(0, 1);
                                p2 = @cpfcnpjsemzeros.Substring(1, 3);
                                p3 = @cpfcnpjsemzeros.Substring(4, 3);
                                p4 = @cpfcnpjsemzeros.Substring(7, 4);
                                p5 = @cpfcnpjsemzeros.Substring(11, 2);
                                resultado = "0" + p1 + "." + p2 + "." + p3 + "/" + p4 + "-" + p5;
                            }
                            else if (cpfcnpjsemzeros.Length == 12)
                            {
                                p1 = @cpfcnpjsemzeros.Substring(0, 3);
                                p2 = @cpfcnpjsemzeros.Substring(3, 3);
                                p3 = @cpfcnpjsemzeros.Substring(6, 4);
                                p4 = @cpfcnpjsemzeros.Substring(10, 2);
                                resultado = p1 + "." + p2 + "/" + p3 + "-" + p4;
                            }
                        }
                        else if (cpfcnpjsemzeros.Length == 11)
                        {
                            p1 = @cpfcnpjsemzeros.Substring(0, 3);
                            p2 = @cpfcnpjsemzeros.Substring(3, 3);
                            p3 = @cpfcnpjsemzeros.Substring(6, 3);
                            p4 = @cpfcnpjsemzeros.Substring(9, 2);

                            resultado = p1 + "." + p2 + "." + p3 + "-" + p4;
                        }
                        else if (cpfcnpjsemzeros.Length < 11)
                        {
                            for (int i = 0; i <= cpfcnpjsemzeros.Length; i += 3)
                            {
                                if (i < (cpfcnpjsemzeros.Length - 3))
                                {
                                    resultado += cpfcnpjsemzeros.Substring(i, 3) + ".";
                                }
                                else
                                {
                                    resultado += cpfcnpjsemzeros.Substring(i, cpfcnpjsemzeros.Length - i);
                                }

                                if (cpfcnpjsemzeros.Length < 4)
                                {
                                    resultado = cpfcnpjsemzeros;
                                }
                            }
                        }
                        @resultado
                    }
                    catch
                    {
                        @item.cpf_cnpj_cliente
                    }
                }
            </td>
            <td align="left">
                @Html.DisplayFor(modelItem => item.marca)
            </td>
            <td align="right">
                @Html.DisplayFor(modelItem => item.chassi)
            </td>
            <td align="right">
                @Html.DisplayFor(modelItem => item.renavam)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.placa)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.valor_divida)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.valor_custas)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.valor_debito_total)
            </td>
            <td align="right">
                @Html.DisplayFor(modelItem => item.ano_exercicio)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.valor_pago_total)
            </td>
            @*<td align="center">
                @Html.DisplayFor(modelItem => item.pagamento_efet_banco)
            </td>*@
        </tr>
    }
</table>